# Don't touch the Dockerfile, only make changes in Dockerfile_template and then run docker_template.php

FROM ubuntu:20.04

EXPOSE {{DOCKER_PORT}}

RUN apt-get update && \
yes Y | apt-get install python3 && \
DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
yes Y | apt-get install php7.4 && \
mkdir {{PYTHON_INTERPRETER_DIR}} && \
mkdir {{PYTHON_INTERPRETER_DIR}}/src && \
mkdir {{PYTHON_INTERPRETER_DIR}}/server

COPY ./server/* {{PYTHON_INTERPRETER_DIR}}/server/

ENTRYPOINT ["php", "{{PYTHON_INTERPRETER_DIR}}/server/server.php", "host={{APP_HOST}}", "port={{DOCKER_PORT}}"]
