# Don't touch the Dockerfile, only make changes in Dockerfile_template and then run docker_template.php

FROM ubuntu:20.04

EXPOSE {{DOCKER_PORT}}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
apt-get install -y python3 && \
apt-get install -y tzdata && \
apt-get install -y php7.4 && \
mkdir {{PYTHON_INTERPRETER_DIR}} && \
mkdir {{PYTHON_INTERPRETER_DIR}}/src && \
mkdir {{PYTHON_INTERPRETER_DIR}}/server

COPY ./server/* {{PYTHON_INTERPRETER_DIR}}/server/

ENTRYPOINT ["php", "{{PYTHON_INTERPRETER_DIR}}/server/server.php", "host={{APP_HOST}}", "port={{DOCKER_PORT}}"]
